### ISSUE TITLE
MPIRUN_FIND directive

### ISSUE THREAD

**Issue by carlilek** [VI4IO/io-500-script#8]
It's often helpful (and permitted) to run a different number of threads for pfind than the rest of the IO500 benchmark. I propose that a variable named $MPIRUN_FIND be added to the config which can then be used in place of $MPIRUN in the generation of the pfind commands, e.g.:

echo $MPIRUN_FIND $BIN/pfind $DATA_DIR -newer $DATA_DIR/timestampfile -size 3901c -name *01* $PFIND_ARGS -s $STONEWALL_TIMER -D rates #-r $DATA_DIR/pfind_results

**Comment by JulianKunkel** [comment]
good suggestion, solved, thx.
